### PR TITLE
Fix for nestjs

### LINKED ISSUE #1: Service with rpc's fail generating
```
undefined:5199
      throw peg$buildStructuredError(
      ^
SyntaxError: Expected "/*", "//", "}", end of line, or whitespace but "r" found.
    at peg$buildStructuredError (eval at compile (C:\git\grpc-microservices\evodesk-grpc\node_modules\pegjs\lib\compiler\index.js:67:29), <anonymous>:657:14)
    at Object.peg$parse [as parse] (eval at compile (C:\git\grpc-microservices\evodesk-grpc\node_modules\pegjs\lib\compiler\index.js:67:29), <anonymous>:5199:13)
    at exportSingleFile (C:\git\grpc-microservices\evodesk-grpc\node_modules\tsbuf\dist\cli\exporter.js:59:31)
    at tsbuf (C:\git\grpc-microservices\evodesk-grpc\node_modules\tsbuf\tsbuf:33:5)
    at executeMe (C:\git\grpc-microservices\evodesk-grpc\node_modules\execute-me\lib\index.js:40:15)
    at Object.<anonymous> (C:\git\grpc-microservices\evodesk-grpc\node_modules\tsbuf\tsbuf:53:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
```

```
syntax = "proto3";
package EvodeskAuth;

service Auth {
    rpc SignJWT(SignJWTRequest) returns (SignJWTResponse) {} //failed on first char 'r'
    rpc VerifyJWT(JWTRequest) returns (VerifyJWTResponse) {}
}

message Error {
    int32 code = 1;
    string message = 2;
}

message Account {
    string _id = 1;
    string login = 2;
    string password = 3;
    string role = 4;
}

message SignJWTRequest {
    string login = 1;
    string password = 2;
}

message SignJWTResponse {
    string jwt = 1;
    Error error = 2;
}

message JWTRequest {
    string jwt = 1;
}

message VerifyJWTResponse {
    bool allow = 1;
    Error error = 2;
}

message JWTObject {
    Account account = 1;
}
```

### PR DESCRIPTION
**Pull request by PhilipMantrov**
Some little fixes for compatibility with grpc implementation from nestjs and one little fix for mongo_db.
Resolve #1

### CODE REVIEW

**Comment by Means88** [comment]
@PhilipMantrov Hello Philip, thanks for your great contribution. The interfaces like
```typescript
interface RpcService {
  rpcMethod(request: RpcRequest): Observable<RpcResponse>;
}
``` 
are generated from `service`, which could be many different types in different projects.

I have an idea that may be more generic for generated interfaces.

```typescript
export interface RpcService {
  rpcMethod: {
    request: RpcRequest;
    response: RpcResponse;
  }
}
```
And we can use the interface with algebraic data type. In your case
```typescript
import { RpcService } from '...';
import { Observable } from 'rxjs';

interface BaseRpcTypeDefinition {
  [key: string]: {
    request: any;
    response: any;
  }
}

type RxRpc<T extends BaseRpcTypeDefinition> = {
  [K in keyof T]: (request: T[K]['request']) => Observable<T[K]['response']>;
};

RxRpc<RpcService>;  // That's what you want
```
For users who use ProtoBuf.js, they can use the interface in the similar way
```typescript
type ProtoBufRpc<T extends BaseRpcTypeDefinition> = {
  [K in keyof T]: (
    request: T[K]['request'],
    callback: (err: any, response: T[K]['response']) => void,
  ) => Promise<T[K]['response']>;
};
```
How do you think of it?

**Comment by PhilipMantrov** [comment]
Oh, i forgot about generic types, ofc we can use it. Its much much better for multi framework compatibility.

**Comment by Means88** [comment]
@PhilipMantrov Hi Phillip, is there anything still going on? Or I'll merge this PR with some modifications.

**Comment by PhilipMantrov** [comment]
You can merge this (after your modifications ofc).

**Pull request merged**
